from .dashboard_view import *
from .home_view import *
from .log_in_view import *
from .log_out_view import *
from .password_view import *
from .profile_view import *
from .sign_up_view import *
from .create_recipe_view import *
from .delete_recipe_view import *
from .delete_user_view import *
from .flag_user_view import *
from .admin_panel_view import *
from .logs_view import *
from .delete_recipe_view import delete_recipe_admin
from .admin_panel_view import admin_panel