# Generated by Django 5.2.7 on 2025-12-07 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_flagged', 'User Flagged for Deletion'), ('user_role_changed', 'User Role Changed'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('recipe_created', 'Recipe Created'), ('recipe_updated', 'Recipe Updated'), ('recipe_deleted', 'Recipe Deleted'), ('admin_action', 'Admin Action'), ('moderator_action', 'Moderator Action'), ('other', 'Other')], default='other', help_text='Type of action performed', max_length=50)),
                ('target_type', models.CharField(blank=True, help_text='Type of object affected (e.g., "User", "Recipe")', max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='ID of the object affected', null=True)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who performed the action', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string from the request', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the action was performed')),
                ('actor', models.ForeignKey(blank=True, help_text='The user who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Log',
                'verbose_name_plural': 'Admin Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='recipes_adm_timesta_5908c8_idx'), models.Index(fields=['actor'], name='recipes_adm_actor_i_2af0d5_idx'), models.Index(fields=['action_type'], name='recipes_adm_action__af6dc4_idx'), models.Index(fields=['target_type', 'target_id'], name='recipes_adm_target__fe70b2_idx')],
            },
        ),
    ]
