# Generated by Django 5.2.7 on 2025-12-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flagged_for_deletion',
            field=models.BooleanField(default=False, help_text='Whether this user has been flagged for deletion by a moderator or admin'),
        ),
    ]
